Loaded dependency [python3/3.7.14]: gcc/10.3.0-binutils-2.36.1
Loaded module: python3/3.7.14

Loading python3/3.7.14
  Loading requirement: gcc/10.3.0-binutils-2.36.1
Loaded module: cuda/10.2
Loaded module: cudnn/v8.3.2.44-prod-cuda-10.2
Loaded module: ffmpeg/4.2.2
2022-11-28 15:42:47.554406: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2022-11-28 15:42:47.554969: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:d8:00.0 name: Tesla V100-PCIE-32GB computeCapability: 7.0
coreClock: 1.38GHz coreCount: 80 deviceMemorySize: 31.75GiB deviceMemoryBandwidth: 836.37GiB/s
2022-11-28 15:42:47.558638: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /appl/cudnn/v8.3.2.44-prod-cuda-10.2/lib:/appl/cuda/10.2/lib64:/appl/python/3.7.14/lib:/appl/gcc/10.3.0-binutils-2.36.1/lib64:/appl/gcc/10.3.0-binutils-2.36.1/lib:/lsf/10.1/linux3.10-glibc2.17-x86_64/lib
2022-11-28 15:42:47.601522: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2022-11-28 15:42:47.629804: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2022-11-28 15:42:47.636819: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2022-11-28 15:42:47.685920: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2022-11-28 15:42:47.692845: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2022-11-28 15:42:47.694134: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /appl/cudnn/v8.3.2.44-prod-cuda-10.2/lib:/appl/cuda/10.2/lib64:/appl/python/3.7.14/lib:/appl/gcc/10.3.0-binutils-2.36.1/lib64:/appl/gcc/10.3.0-binutils-2.36.1/lib:/lsf/10.1/linux3.10-glibc2.17-x86_64/lib
2022-11-28 15:42:47.694151: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1598] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2022-11-28 15:42:47.694578: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2022-11-28 15:42:47.710402: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2600000000 Hz
2022-11-28 15:42:47.710507: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x80cc6f0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2022-11-28 15:42:47.710519: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2022-11-28 15:42:47.711873: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-11-28 15:42:47.711890: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      
Traceback (most recent call last):
  File "/zhome/0f/f/137116/Desktop/DeepLearningProject/SparseVAE-Cell-Images/src/train-convvae.py", line 37, in <module>
    reload_model=not args.do_not_resume)
  File "/zhome/0f/f/137116/Desktop/DeepLearningProject/SparseVAE-Cell-Images/src/models/base_model.py", line 213, in run_training
    train_loss, logs = self.train(train_loader, epoch, logging_func)
  File "/zhome/0f/f/137116/Desktop/DeepLearningProject/SparseVAE-Cell-Images/src/models/base_model.py", line 110, in train
    loss, log = self.step(data, train=True)
  File "/zhome/0f/f/137116/Desktop/DeepLearningProject/SparseVAE-Cell-Images/src/models/base_model.py", line 46, in step
    output = self.model(data)
  File "/zhome/0f/f/137116/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/zhome/0f/f/137116/Desktop/DeepLearningProject/SparseVAE-Cell-Images/src/models/conv_vae.py", line 96, in forward
    mu, logvar = self.encode(x)
  File "/zhome/0f/f/137116/Desktop/DeepLearningProject/SparseVAE-Cell-Images/src/models/conv_vae.py", line 79, in encode
    features = self.conv_encoder(x)
  File "/zhome/0f/f/137116/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/zhome/0f/f/137116/.local/lib/python3.7/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/zhome/0f/f/137116/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/zhome/0f/f/137116/.local/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/zhome/0f/f/137116/.local/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 460, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [32, 13872]
